package com.bjzc.greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjzc.greendao.entity.PersonInfor;
import com.bjzc.greendao.entity.User;

import com.bjzc.greendao.dao.PersonInforDao;
import com.bjzc.greendao.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personInforDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PersonInforDao personInforDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personInforDaoConfig = daoConfigMap.get(PersonInforDao.class).clone();
        personInforDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personInforDao = new PersonInforDao(personInforDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PersonInfor.class, personInforDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        personInforDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PersonInforDao getPersonInforDao() {
        return personInforDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
